const DrinkArray = [
    // Americanos
    [
        ["../../assets/dutch_bro_drinks/Americanos/Americano.png", "Americano"],
        ["../../assets/dutch_bro_drinks/Americanos/Cafe_Au_Lait_Americano.png", "Cafe Au Lait Americano"],
        ["../../assets/dutch_bro_drinks/Americanos/Keto_Americano.png", "Keto Americano"]
    ],
    // Breves
    [
        ["../../assets/dutch_bro_drinks/Breves/911_Breve.png", "911 Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Almond_Bar_Breve.png", "Almond Bar Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Amaretto_Breve.png", "Amaretto Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Annihilator_Breve.png", "Annihilator Breve"],
        ["../../assets/dutch_bro_drinks/Breves/B-52_Breve.png", "B-52 Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Banana_Bread_Breve.png", "Banana Bread Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Banana_Cream_Pie_Breve.png", "Banana Cream Pie Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Banana_Split_Breve.png", "Banana Split Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Ba-Nay-Nay_Breve.png", "Ba-Nay-Nay Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Billy_Jean_Breve.png", "Billy Jean Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Birthday_Cake_Breve.png", "Birthday Cake Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Black_Forest_Breve.png", "Black Forest Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Breve.png", "Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cake_Batter_Breve.png", "Cake Batter Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cherry_Blossom_Breve.png", "Cherry Blossom Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cinnamon_Dolce_Breve.png", "Cinnamon Dolce Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cinammon_Roll_Breve.png", "Cinnamon Roll Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cookie_Breve.png", "Cookie Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cookies_N_Cream_Breve.png", "Cookies & Cream Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Cotton_Candy_Breve.png", "Cotton Candy Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Crazy_Hawaiian_Breve.png", "Crazy Hawaiian Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Dream_Weaver_Breve.png", "Dream Weaver Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Dutch_Canyon_Breve.png", "Dutch Canyon Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Flapjack_Breve.png", "Flapjack Breve"],
        ["../../assets/dutch_bro_drinks/Breves/French_Toast_Breve.png", "French Toast Breve"],
        ["../../assets/dutch_bro_drinks/Breves/French_Vanilla_Breve.png", "French Vanilla Bean Breve"],
        ["../../assets/dutch_bro_drinks/Breves/German_Chocolate_Breve.png", "German Chocolate Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Golden_Eagle_Breve.png", "Golden Eagle Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Grasshopper_Breve.png", "Grasshopper Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Horchata_Breve.png", "Horchata Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Irie_Breve.png", "Irie Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Islander_Breve.png", "Islander Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Jelly_Donut_Breve.png", "Jelly Donut Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Kicker_Breve.png", "Kicker Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Molten_Lava_Breve.png", "Molten Lava Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Ninja_Breve.png", "Ninja Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Nutty_Irishman_Breve.png", "Nutty Irishman Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Peach_Cobbler_Breve.png", "Peach Cobbler Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Peppermint_Bark_Breve.png", "Peppermint Bark Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Raspberry_Truffle_Breve.png", "Raspberry Truffle Breve"],
        ["../../assets/dutch_bro_drinks/Breves/S'mores_Breve.png", "S'Mores Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Snickerdoodle_Breve.png", "Snickerdoodle Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Sugar_Cookie_Breve.png", "Sugar Cookie Breve"],
        ["../../assets/dutch_bro_drinks/Breves/The_Bob_Breve.png", "The Bob Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Toasted_Mellow_Breve.png", "Toasted Mellow Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Trifecta_Breve.png", "Trifecta Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Tuxedo_Breve.png", "Tuxedo Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Vanilla_Bean_Breve.png", "Vanilla Bean Breve"],
        ["../../assets/dutch_bro_drinks/Breves/Wallaby_Breve.png", "Wallaby Breve"],
        ["../../assets/dutch_bro_drinks/Breves/White_Angel_Breve.png", "White Angel Breve"],
        ["../../assets/dutch_bro_drinks/Breves/White_Zombie_Breve.png", "White Zombie Breve"]
    ],
    // Chais
    [
        ["../../assets/dutch_bro_drinks/Chais/Chai.png", "Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Christmas_Morning_Chai.png", "Christmas Morning Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Cinnamon_Dolce_Chai.png", "Cinnamon Dolce Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Cinnamon_Roll_Chai.png", "Cinnamon Roll Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Dirty_Chai.png", "Dirty Chai"],
        ["../../assets/dutch_bro_drinks/Chais/French_Toast_Chai.png", "French Toast Chai"],
        ["../../assets/dutch_bro_drinks/Chais/French_Vanilla_Bean_Chai.png", "Vanilla Bean Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Golden_Eagle_Chai.png", "Eagle Chai"],
        ["../../assets/dutch_bro_drinks/Chais/Horchata_Chai.png", "Horchata Chai"],
        ["../../assets/dutch_bro_drinks/Chais/White_Zombie_Chai.png", "White Zombie Chai"]
    ],
    // Cold Brew
    [
        ["../../assets/dutch_bro_drinks/Cold Brew/911_Cold_Brew.png", "911 Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Annihilator_Cold_Brew.png", "Annihilator Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Caramelizer_Cold_Brew.png", "Caramelizer Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Cocomo_Cold_Brew.png", "Cocomo Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Cold_Brew.png", "Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Double_Chocolate_Mocha_Cold_Brew.png", "Double Chocolate Mocha Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Double_Torture_Cold_Brew.png", "Double Torture Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Keto_Cold_Brew.png", "Keto Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/Kicker_Cold_Brew.png", "Kicker Cold Brew"],
        ["../../assets/dutch_bro_drinks/Cold Brew/White_Mocha_Cold_Brew.png", "White Mocha Cold Brew"]
    ],
    // Freezes
    [
        ["../../assets/dutch_bro_drinks/Freezes/911_Freeze.png", "911 Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Almond_Bar_Freeze.png", "Almond Bar Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Amaretto_Freeze.png", "Amaretto Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Annihilator_Freeze.png", "Annihilator Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/B-52_Freeze.png", "B-52 Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Banana_Bread_Freeze.png", "Banana Bread Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Banana_Cream_Pie_Freeze.png", "Banana Cream Pie Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Banana_Split_Freeze.png", "Banana Split Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Ba-Nay-Nay_Freeze.png", "Ba-Nay-Nay Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Billy_Jean_Freeze.png", "Billy Jean Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Birthday_Cake_Freeze.png", "Birthday Cake Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Black_Forest_Freeze.png", "Black Forest Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cake_Batter_Freeze.png", "Cake Batter Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Caramelizer_Freeze.png", "Caramelizer Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cherry_Blossom_Freeze.png", "Cherry Blossom Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cinnamon_Dolce_Freeze.png", "Cinnamon Dolce Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cinnamon_Roll_Freeze.png", "Cinnamon Roll Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cocomo_Freeze.png", "Cocomo Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cookie_Freeze.png", "Cookie Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Cotton_Candy_Freeze.png", "Cotton Candy Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Crazy_Hawaiian_Freeze.png", "Crazy Hawaiian Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Double_Chocolate_Mocha_Freeze.png", "Double Chocolate Mocha Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Double_Torture_Freeze.png", "Double Torture Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Dream_Weaver_Freeze.png", "Dream Weaver Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Dutch_Canyon_Freeze.png", "Dutch Canyon Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Flapjack_Freeze.png", "Flapjack Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/French_Toast_Freeze.png", "French Toast Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/French_Vanilla_Bean_Freeze.png", "French Vanilla Bean Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/German_Chocolate_Freeze.png", "German Chocolate Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Golden_Eagle_Freeze.png", "Golden Eagle Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Grasshopper_Freeze.png", "Grasshopper Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Horchata_Freeze.png", "Horchata Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Irie_Freeze.png", "Irie Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Islander_Freeze.png", "Islander Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Jelly_Donut_Freeze.png", "Jelly Donut Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Kicker_Freeze.png", "Kicker Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Molten_Lava_Freeze.png", "Molten Lava Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Ninja_Freeze.png", "Ninja Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Nutty_Irishman_Freeze.png", "Nutty Irishman Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Peach_Cobbler_Freeze.png", "Peach Cobbler Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Peppermint_Bark_Freeze.png", "Peppermint Bark Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Picture_Perfect_Freeze.png", "Picture Perfect Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Raspberry_Truffle_Freeze.png", "Raspberry Truffle Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/S'mores_Freeze.png", "S'Mores Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Snickerdoodle_Freeze.png", "Snickerdoodle Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Sugar_Cookie_Freeze.png", "Sugar Cookie Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/The_Bob_Freeze.png", "The Bob Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Toasted_Mellow_Freeze.png", "Toasted Mellow Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Trifecta_Freeze.png", "Trifecta Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Tuxedo_Freeze.png", "Tuxedo Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Vanilla_Bean_Freeze.png", "Vanilla Bean Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/Wallaby_Freeze.png", "Wallaby Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/White_Angel_Freeze.png", "White Angel Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/White_Mocha_Freeze.png", "White Mocha Freeze"],
        ["../../assets/dutch_bro_drinks/Freezes/White_Zombie_Freeze.png", "White Zombie Freeze"]
        
    ],
    // Frosts
    [
        ["../../assets/dutch_bro_drinks/Frosts/Aftershock_Frost.png", "Aftershock Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Almond_Bar_Frost.png", "Almond Bar Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Amaretto_Frost.png", "Amaretto Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Aquaberry_Frost.png", "Aquaberry Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Astronaut_Frost.png", "Astronaut Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/B-52_Frost.png", "B-52 Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Banana_Bread_Frost.png", "Banana Bread Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Banana_Cream_Pie_Frost.png", "Banana Cream Pie Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Banana_Split_Frost.png", "Banana Split Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Ba-Nay-Nay_Frost.png", "Ba-Nay-Nay Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Billy_Jean_Frost.png", "Billy Jean Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Birthday_Cake_Frost.png", "Birthday Cake Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Black_Forest_Frost.png", "Black Forest Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Bubblegum_Frost.png", "Bubblegum Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cake_Batter_Frost.png", "Cake Batter Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cherry_Blossom_Frost.png", "Cherry Blossom Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cinnamon_Dolce_Frost.png", "Cinnamon Dolce Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cinnamon_Roll_Frost.png", "Cinnamon Roll Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cookie_Frost.png", "Cookie Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Coral_Reef_Frost.png", "Coral Reef Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Cotton_Candy_Frost.png", "Cotton Candy Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Crazy_Hawaiian_Frost.png", "Crazy Hawaiian Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Dinosaur_Egg_Frost.png", "Dinosaur Egg Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Double_Rainbro_Frost.png", "Double Rainbro Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Dragon_Slayer_Frost.png", "Dragon Slayer Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Dream_Weaver_Frost.png", "Dream Weaver Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Dutch_Canyon_Frost.png", "Dutch Canyon Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Dutch_Mojito_Frost.png", "Dutch Mojito Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Eclipse_Frost.png", "Eclipse Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Electric_Berry_Frost.png", "Electric Berry Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Fire_Lizard_Frost.png", "Fire Lizard Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Flapjack_Frost.png", "Flapjack Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Freedom_Frost.png", "Freedom Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/French_Toast_Frost.png", "French Toast Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/French_Vanilla_Bean_Frost.png", "French Vanilla Bean Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Galaxy_Fish_Frost.png", "Galaxy Fish Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Gem_Berry_Frost.png", "Gem Berry Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/German_Chocolate_Frost.png", "German Chocolate Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Golden_Eagle_Frost.png", "Golden Eagle Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Grape_Frost.png", "Grape Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Grasshopper_Frost.png", "Grasshopper Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Gummy_Bear_Frost.png", "Gummy Bear Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Hawaiian_Frost.png", "Hawaiian Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Horchata_Frost.png", "Horchata Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Hyperchrome_Frost.png", "Hyperchrome Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Irie_Frost.png", "Irie Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Islander_Frost.png", "Islander Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Jelly_Donut_Frost.png", "Jelly Donut Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Lazer_Cat_Frost.png", "Lazer Cat Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Majestic_Forest_Frost.png", "Majestic Forest Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Marmalade_Frost.png", "Marmalade Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Midnight_Frost.png", "Midnight Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Molten_Lava_Frost.png", "Molten Lava Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Ninja_Frost.png", "Ninja Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Nutty_Irishman_Frost.png", "Nutty Irishman Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/OG_Gummy_Bear_Frost.png", "OG Gummy Bear Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Orangesicle_Frost.png", "Orangesicle Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Palm_Beach_Frost.png", "Palm Beach Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Palm_Tree_Frost.png", "Palm Tree Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Passion_Water_Frost.png", "Passion Water Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Peach_Cobbler_Frost.png", "Peach Cobbler Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Peach_Ring_Frost.png", "Peach Ring Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Peppermint_Bark_Frost.png", "Peppermint Bark Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Pink_Flamingo_Frost.png", "Pink Flamingo Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Raspberry_Truffle_Frost.png", "Raspberry Truffle Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Ray_of_Sunshine_Frost.png", "Ray of Sunshine Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Red,_White___Blue_Frost.png", "Red, White & Blue Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Rocky_Point_Frost.png", "Rocky Point Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Shark_Attack_Frost.png", "Shark Attack Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/S_Mores_Frost.png", "S'Mores Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Snickerdoodle_Frost.png", "Snickerdoodle Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Starry_Night_Frost.png", "Starry Night Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Stop_Light_Frost.png", "Stop Light Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Sugar_Cookie_Frost.png", "Sugar Cookie Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Sweet_Sunrise_Frost.png", "Sweet Sunrise Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/The_Bob_Frost.png", "The Bob Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/The_Juice_Frost.png", "The Juice Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/The_Vampire_Slayer_Frost.png", "The Vampire Slayer Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Tigers_Blood_Frost.png", "Tigers Blood Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Toasted_Mellow_Frost.png", "Toasted Mellow Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Tricky_Tre_Frost.png", "Tricky Tre Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Trifecta_Frost.png", "Trifecta Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Trixie_Frost.png", "Trixie Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Tropical_Frost.png", "Tropical Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Tuxedo_Frost.png", "Tuxedo Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Unicorn_Blood_Frost.png", "Unicorn Blood Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Vanilla_Bean_Frost.png", "Vanilla Bean Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/Wallaby_Frost.png", "Wallaby Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/White_Angel_Frost.png", "White Angel Frost"],
        ["../../assets/dutch_bro_drinks/Frosts/White_Zombie_Frost.png", "White Zombie Frost"]
        
    ],
    // Hot Cocoa
    [
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Almond_Bar_Hot_Cocoa.png", "Almond Bar Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Amaretto_Hot_Cocoa.png", "Amaretto Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/B-52_Hot_Cocoa.png", "B-52 Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Banana_Bread_Hot_Cocoa.png", "Banana Bread Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Banana_Cream_Pie_Hot_Cocoa.png", "Banana Cream Pie Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Banana_Split_Hot_Cocoa.png", "Banana Split Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Ba-Nay-Nay_Hot_Cocoa.png", "Ba-Nay-Nay Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Billy_Jean_Hot_Cocoa.png", "Billy Jean Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Birthday_Cake_Hot_Cocoa.png", "Birthday Cake Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Black_Forest_Hot_Cocoa.png", "Black Forest Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cake_Batter_Hot_Cocoa.png", "Cake Batter Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cherry_Blossom_Hot_Cocoa.png", "Cherry Blossom Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cinammon_Dolce_Hot_Cocoa.png", "Cinammon Dolce Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cinammon_Roll_Hot_Cocoa.png", "Cinammon Roll Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cookie_Hot_Cocoa.png", "Cookie Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Cotton_Candy_Hot_Cocoa.png", "Cotton Candy Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Crazy_Hawaiian_Hot_Cocoa.png", "Crazy Hawaiian Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Drean_Weaver_Hot_Cocoa.png", "Drean Weaver Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Dutch_Canyon_Hot_Cocoa.png", "Dutch Canyon Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Flapjack_Hot_Cocoa.png", "Flapjack Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/French_Toast_Hot_Cocoa.png", "French Toast Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/French_Vanilla_Bean_Hot_Cocoa.png", "French Vanilla Bean Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/German_Chocolate_Hot_Cocoa.png", "German Chocolate Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Golden_Eagle_Hot_Cocoa.png", "Golden Eagle Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Grasshopper_Hot_Cocoa.png", "Grasshopper Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Hot_Cocoa.png", "Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Irie_Hot_Cocoa.png", "Irie Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Islander_Hot_Cocoa.png", "Islander Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Jelly_Donut_Hot_Cocoa.png", "Jelly Donut Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Molten_Lava_Hot_Cocoa.png", "Molten Lava Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Ninja_Hot_Cocoa.png", "Ninja Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Nutty_Irishman_Hot_Cocoa.png", "Nutty Irishman Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Peppermint_Bark_Hot_Cocoa.png", "Peppermint Bark Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Raspberry_Truffle_Hot_Cocoa.png", "Raspberry Truffle Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/S'Mores_Hot_Cocoa.png", "S'Mores Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Snickerdoodle_Hot_Cocoa.png", "Snickerdoodle Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Sugar_Cookie_Hot_Cocoa.png", "Sugar Cookie Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/The_Bob_Hot_Cocoa.png", "The Bob Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Toasted_Mellow_Hot_Cocoa.png", "Toasted Mellow Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Trifecta_Hot_Cocoa.png", "Trifecta Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Tuxedo_Hot_Cocoa.png", "Tuxedo Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Vanilla_Bean_Hot_Cocoa.png", "Vanilla Bean Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/Wallaby_Hot_Cocoa.png", "Wallaby Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/White_Angel_Hot_Cocoa.png", "White Angel Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Hot Cocoa/White_Zombie_Hot_Cocoa.png", "White Zombie Hot Cocoa"]
        
    ],
    // Kids Drinks
    [
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Aftershock_Frost.png", "Aftershock Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Almond_Bar_Frost.png", "Almond Bar Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Amaretto_Frost.png", "Amaretto Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Aquaberry_Frost.png", "Aquaberry Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Astronaut_Frost.png", "Astronaut Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_B-52_Frost.png", "B-52 Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Banana_Bread_Frost.png", "Banana Bread Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Banana_Cream_Pie_Frost.png", "Banana Cream Pie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Banana_Split_Frost.png", "Banana Split Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Ba-Nay-Nay_Frost.png", "Ba-Nay-Nay Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Billy_Jean_Frost.png", "Billy Jean Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Birthday_Cake_Frost.png", "Birthday Cake Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Black_Forest_Frost.png", "Black Forest Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Bubblegum_Frost.png", "Bubblegum Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cake_Batter_Frost.png", "Cake Batter Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cherry_Blossom_Frost.png", "Cherry Blossom Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cinnamon_Dolce_Frost.png", "Cinnamon Dolce Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cinnamon_Roll_Frost.png", "Cinnamon Roll Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cookie_Frost.png", "Cookie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Coral_Reef_Frost.png", "Coral Reef Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Cotton_Candy_Frost.png", "Cotton Candy Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Crazy_Hawaiian_Frost.png", "Crazy Hawaiian Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Dinosaur_Egg_Frost.png", "Dinosaur Egg Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Double_Rainbro_Frost.png", "Double Rainbro Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Dragon_Slayer_Frost.png", "Dragon Slayer Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Dream_Weaver_Frost.png", "Dream Weaver Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Dutch_Canyon_Frost.png", "Dutch Canyon Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Dutch_Mojito_Frost.png", "Dutch Mojito Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Electric_Berry_Frost.png", "Electric Berry Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Fire_Lizard_Frost.png", "Fire Lizard Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Flap_Jack_Frost.png", "Flapjack Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Freedom_Frost.png", "Freedom Frost Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_French_Toast_Frost.png", "French Toast Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_French_Vanilla_Bean_Frost.png", "French Vanilla Bean Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Galaxy_Fish_Frost.png", "Galaxy Fish Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Gem_Berry_Frost.png", "Gem Berry Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_German_Chocolate_Frost.png", "German Chocolate Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Golden_Eagle_Frost.png", "Golden Eagle Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Grape_Frost.png", "Grape Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Grasshopper_Frost.png", "Grasshopper Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Gummy_Bear_Frost.png", "Gummy Bear Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Hawaiian_Frost.png", "Hawaiian Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Horchata_Frost.png", "Horchata Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Hyperchrome_Frost.png", "Hyperchrome Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Irie_Frost.png", "Irie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Islander_Frost.png", "Islander Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Jelly_Donut_Frost.png", "Jelly Donut Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Lazer_Cat_Frost.png", "Lazer Cat Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Majestic_Forest_Frost.png", "Majestic Forest Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Marmalade_Frost.png", "Marmalade Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Midnight_Frost.png", "Midnight Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Molten_Lava_Frost.png", "Molten Lava Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Ninja_Frost.png", "Ninja Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Nutty_Irishman_Frost.png", "Nutty Irishman Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_OG_Gummy_Bear_Frost.png", "OG Gummy Bear Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Orangesicle_Frost.png", "Orangesicle Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Palm_Beach_Frost.png", "Palm Beach Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Palm_Tree_Frost.png", "Palm Tree Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Passion_Water_Frost.png", "Passion Water Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Peach_Cobbler_Frost.png", "Peach Cobbler Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Peach_Ring_Frost.png", "Peach Ring Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Peppermint_Bark_Frost.png", "Peppermint Bark Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Pink_Flamingo_Frost.png", "Pink Flamingo Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Raspberry_Truffle_Frost.png", "Raspberry Truffle Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Ray_of_Sunshine_Frost.png", "Ray of Sunshine Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Red,_White_&_Blue_Frost.png", "Red, White & Blue Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Rocky_Point_Frost.png", "Rocky Point Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Shark_Attack_Frost.png", "Shark Attack Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_S'Mores_Frost.png", "S'Mores Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Snickerdoodle_Frost.png", "Snickerdoodle Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Starry_Night_Frost.png", "Starry Night Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Stop_Light_Frost.png", "Stop Light Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Sugar_Cookie_Frost.png", "Sugar Cookie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Sweet_Sunrise_Frost.png", "Sweet Sunrise Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_The_Bob_Frost.png", "The Bob Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_The_Juice_Frost.png", "The Juice Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_The_Vampire_Slayer_Frost.png", "The Vampire Slayer Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Tigers_Blood_Frost.png", "Tigers Blood Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Toasted_Mellow_Frost.png", "Toasted Mellow Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Tricky_Tre_Frost.png", "Tricky Tre Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Trifecta_Frost.png", "Trifecta Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Trixie_Frost.png", "Trixie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Tropical_Frost.png", "Tropical Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Tuxedo_Frost.png", "Tuxedo Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Unicorn_Blood_Frost.png", "Unicorn Blood Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Vanilla_Bean_Frost.png", "Vanilla Bean Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Wallaby_Frost.png", "Wallaby Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_White_Angel_Frost.png", "White Angel Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_White_Zombie_Frost.png", "White Zombie Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kidst_Eclipse_Frost.png", "Kids Eclipse Frost"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Blueberry_Pomegranate_Smoothie.png", "Kids Blueberry Pomegranate Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Caramel_Apple_Smoothie.png", "Kids Caramel Apple Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Green_Apple_Smoothie.png", "Kids Green Apple Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Mango_Smoothie.png", "Kids Mango Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Peach_Smoothie.png", "Kids Peach Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Strawberry_Smoothie.png", "Kids Strawberry Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Wildberry_Smoothie.png", "Kids Wildberry Smoothie"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Lemonade.png", "Kids Lemonade"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Hot_Cocoa_Hot.png", "Kids Hot Cocoa"],
        ["../../assets/dutch_bro_drinks/Kids Drinks/Kids_Hot_Cocoa_Amaretto_Hot.png", "Kids Amaretto Hot Cocoa"]
        
    ],
    // Latte
    [
        ["../../assets/dutch_bro_drinks/Latte/Almond_Bar_Latte.png", "Almond Bar Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Amaretto_Latte.png", "Amaretto Latte"],
        ["../../assets/dutch_bro_drinks/Latte/B-52_Latte.png", "B-52 Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Banana_Bread_Latte.png", "Banana Bread Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Banana_Cream_Pie_Latte.png", "Banana Cream Pie Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Banana_Split_Latte.png", "Banana Split Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Ba-Nay-Nay_Latte.png", "Ba-Nay-Nay Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Billy_Jean_Latte.png", "Billy Jean Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Birthday_Cake_Latte.png", "Birthday Cake Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Black_Forest_Latte.png", "Black Forest Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cake_Batter_Latte.png", "Cake Batter Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cherry_Blossom_Latte.png", "Cherry Blossom Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cinnamon_Dolce_Latte.png", "Cinnamon Dolce Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cinammon_Roll_Latte.png", "Cinammon Roll Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cookie_Latte.png", "Cookie Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Cotton_Candy_Latte.png", "Cotton Candy Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Crazy_Hawaiian_Latte.png", "Crazy Hawaiian Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Dream_Weaver_Latte.png", "Dream Weaver Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Dutch_Canyon_Latte.png", "Dutch Canyon Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Flapjack_Latte.png", "Flapjack Latte"],
        ["../../assets/dutch_bro_drinks/Latte/French_Toast_Latte.png", "French Toast Latte"],
        ["../../assets/dutch_bro_drinks/Latte/French_Vanilla_Bean_Latte.png", "French Vanilla Bean Latte"],
        ["../../assets/dutch_bro_drinks/Latte/German_Chocolate_Latte.png", "German Chocolate Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Golden_Eagle_Latte.png", "Golden Eagle Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Grasshopper_Latte.png", "Grasshopper Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Horchata_Latte.png", "Horchata Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Irie_Latte.png", "Irie Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Islander_Latte.png", "Islander Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Jelly_Donut_Latte.png", "Jelly Donut Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Latte.png", "Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Molten_Lava_Latte.png", "Molten Lava Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Ninja_Latte.png", "Ninja Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Nutty_Irishman_Latte.png", "Nutty Irishman Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Peach_Cobbler_Latte.png", "Peach Cobbler Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Peppermint_Bark_Latte.png", "Peppermint Bark Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Raspberry_Truffle_Latte.png", "Raspberry Truffle Latte"],
        ["../../assets/dutch_bro_drinks/Latte/S'Mores_Latte.png", "S'Mores Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Snickerdoodle_Latte.png", "Snickerdoodle Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Sugar_Cookie_Latte.png", "Sugar Cookie Latte"],
        ["../../assets/dutch_bro_drinks/Latte/The_Bob_Latte.png", "The Bob Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Toasted_Mellow_Latte.png", "Toasted Mellow Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Trifecta_Latte.png", "Trifecta Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Tuxedo_Latte.png", "Tuxedo Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Vanilla_Bean_Latte.png", "Vanilla Bean Latte"],
        ["../../assets/dutch_bro_drinks/Latte/Wallaby_Latte.png", "Wallaby Latte"],
        ["../../assets/dutch_bro_drinks/Latte/White_Angel_Latte.png", "White Angel Latte"],
        ["../../assets/dutch_bro_drinks/Latte/White_Zombie_Latte.png", "White Zombie Latte"]
       
    ],
    // Lemonades
    [
        ["../../assets/dutch_bro_drinks/Lemonades/Aftershock_Lemonade.png", "Aftershock Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Amaretto_Lemonade.png", "Amaretto Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Aquaberry_Lemonade.png", "Aquaberry Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Astronaut_Lemonade.png", "Astronaut Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Double_Rainbro_Lemonade.png", "Double Rainbro Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Dragon_Slayer_Lemonade.png", "Dragon Slayer Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Dutch_Mojito_Lemonade.png", "Dutch Mojito Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Electric_Berry_Lemonade.png", "Electric Berry Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Fire_Lizard_Lemonade.png", "Fire Lizard Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Galaxy_Fish_Lemonade.png", "Galaxy Fish Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Gem_Berry_Lemonade.png", "Gem Berry Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Green_Tea_Lemonade.png", "Green Tea Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Hawaiian_Lemonade.png", "Hawaiian Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Hyperchrome_Lemonade.png", "Hyperchrome Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Irie_Lemonade.png", "Irie Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Laser_Cat_Lemonade.png", "Laser Cat Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Lemonade.png", "Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Lemonade_Iced_Grape.png", "Grape Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Majestic_Forest_Lemonade.png", "Majestic Forest Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Marmalade_Lemonade.png", "Marmalade Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Midnight_Lemonade.png", "Midnight Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/OG_Gummy_Bear_Lemonade.png", "OG Gummy Bear Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Orangesicle_Lemonade.png", "Orangesicle Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Palm_Beach_Lemonade.png", "Palm Beach Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Palm_Tree_Lemonade.png", "Palm Tree Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Passion_Water_Lemonade.png", "Passion Water Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Ray_of_Sunshine_Lemonade.png", "Ray of Sunshine Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Rocky_Point_Lemonade.png", "Rocky Point Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Shark_Attack_Lemonade.png", "Shark Attack Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Starry_Night_Lemonade.png", "Starry Night Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Stop_Light_Lemonade.png", "Stop Light Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Sweet_Sunrise_Lemonade.png", "Sweet Sunrise Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/The_Eclipse_Lemonade.png", "The Eclipse Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/The_Juice_Lemonade.png", "The Juice Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/The_Vampire_Slayer_Lemonade.png", "The Vampire Slayer Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Tigers_Blood_Lemonade.png", "Tigers Blood Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Tricky_Tre_Lemonade.png", "Tricky Tre Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Trixie_Lemonade.png", "Trixie Lemonade"],
        ["../../assets/dutch_bro_drinks/Lemonades/Tropical_Lemonade.png", "Tropical Lemonade"]
        
    ],
    // Mochas
    [
        ["../../assets/dutch_bro_drinks/Mochas/Almond_Bar_Mocha.png", "Almond Bar Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Amaretto_Mocha.png", "Amaretto Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/B-52_Mocha.png", "B-52 Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Banana_Bread_Mocha.png", "Banana Bread Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Banana_Cream_Pie_Mocha.png", "Banana Cream Pie Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Banana_Split_Mocha.png", "Banana Split Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Ba-Nay-Nay_Mocha.png", "Ba-Nay-Nay Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Billy_Jean_Mocha.png", "Billy Jean Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Birthday_Cake_Mocha.png", "Birthday Cake Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Black_Forest_Mocha.png", "Black Forest Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cake_Batter_Mocha.png", "Cake Batter Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Caramelizer_Mocha.png", "Caramelizer Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cherry_Blossom_Mocha.png", "Cherry Blossom Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cinnamon_Dolce_Mocha.png", "Cinnamon Dolce Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cinnamon_Roll_Mocha.png", "Cinnamon Roll Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cocomo_Mocha.png", "Cocomo Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cookie_Mocha.png", "Cookie Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Cotton_Candy_Mocha.png", "Cotton Candy Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Crazy_Hawaiian_Mocha.png", "Crazy Hawaiian Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Double_Chocolate_Mocha.png", "Double Chocolate Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Double_Torture_Mocha.png", "Double Torture Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Dream_Weaver_Mocha.png", "Dream Weaver Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Dutch_Canyon_Mocha.png", "Dutch Canyon Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Flapjack_Mocha.png", "Flapjack Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/French_Toast_Mocha.png", "French Toast Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/French_Vanilla_Bean_Mocha.png", "French Vanilla Bean Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/German_Chocolate_Mocha.png", "German Chocolate Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Golden_Eagle_Mocha.png", "Golden Eagle Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Grasshopper_Mocha.png", "Grasshopper Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Horchata_Mocha.png", "Horchata Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Irie_Mocha.png", "Irie Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Islander_Mocha.png", "Islander Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Jelly_Donut_Mocha.png", "Jelly Donut Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Mocha.png", "Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Molten_Lava_Mocha.png", "Molten Lava Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Ninja_Mocha.png", "Ninja Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Nutty_Irishman_Mocha.png", "Nutty Irishman Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Peach_Cobbler_Mocha.png", "Peach Cobbler Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Peppermint_Bark_Mocha.png", "Peppermint Bark Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Raspberry_Truffle_Mocha.png", "Raspberry Truffle Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/S'Mores_Mocha.png", "S'Mores Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Snickerdoodle_Mocha.png", "Snickerdoodle Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Sugar_Cookie_Mocha.png", "Sugar Cookie Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/The_Bob_Mocha.png", "The Bob Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Toasted_Mellow_Mocha.png", "Toasted Mellow Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Trifecta_Mocha.png", "Trifecta Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Tuxedo_Mocha.png", "Tuxedo Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Vanilla_Bean_Mocha.png", "Vanilla Bean Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/Wallaby_Mocha.png", "Wallaby Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/White_Angel_Mocha.png", "White Angel Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/White_Mocha_Mocha.png", "White Mocha"],
        ["../../assets/dutch_bro_drinks/Mochas/White_Zombie_Mocha.png", "White Zombie Mocha"]
        
    ],
    // Rebels
    [
        ["../../assets/dutch_bro_drinks/Rebels/Aftershock_Rebel.png", "Aftershock Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Amaretto_Rebel.png", "Amaretto Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Aquaberry_Rebel.png", "Aquaberry Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Astronaut_Rebel.png", "Astronaut Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Bubblegum_Rebel.png", "Bubblegum Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Cherry_Blossom_Rebel.png", "Cherry Blossom Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Cotton_Candy_Rebel.png", "Cotton Candy Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Dinosaur_Egg_Rebel.png", "Dinosaur Egg Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Double_Rainbro_Rebel.png", "Double Rainbro Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Dragon_Slayer_Rebel.png", "Dragon Slayer Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Dutch_Mojito_Rebel.png", "Dutch Mojito Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Eclipse_Rebel.png", "Eclipse Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Electric_Berry_Rebel.png", "Electric Berry Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Fire_Lizard_Rebel.png", "Fire Lizard Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Freedom_Rebel.png", "Freedom Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Galaxy_Fish_Rebel.png", "Galaxy Fish Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Gem_Berry_Rebel.png", "Gem Berry Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Gummy_Bear_Rebel.png", "Gummy Bear Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Hawaiian_Rebel.png", "Hawaiian Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Hyperchrome_Rebel.png", "Hyperchrome Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Iced_Grape_Rebel.png", "Grape Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Irie_Rebel.png", "Irie Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Lazer_Cat_Rebel.png", "Lazer Cat Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Majestic_Forest_Rebel.png", "Majestic Forest Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Marmalade_Rebel.png", "Marmalade Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Midnight_Rebel.png", "Midnight Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/OG_Gummy_Bear_Rebel.png", "OG Gummy Bear Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Orangesicle_Rebel.png", "Orangesicle Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Palm_Beach_Rebel.png", "Palm Beach Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Palm_Tree_Rebel.png", "Palm Tree Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Passion_Water_Rebel.png", "Passion Water Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Peach_Cobbler_Rebel.png", "Peach Cobbler Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Peach_Ring_Rebel.png", "Peach Ring Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Pink_Flamingo_Rebel.png", "Pink Flamingo Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Ray_of_Sunshine_Rebel.png", "Ray of Sunshine Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Red,_White_&_Blue_Rebel.png", "Red, White & Blue Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Rocky_Point_Rebel.png", "Rocky Point Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Shark_Attack_Rebel.png", "Shark Attack Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Starry_Night_Rebel.png", "Starry Night Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Stop_Light_Rebel.png", "Stop Light Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Sweet_Sunrise_Rebel.png", "Sweet Sunrise Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/The_Juice_Rebel.png", "The Juice Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/The_Vampire_Slayer_Rebel.png", "The Vampire Slayer Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Tigers_Blood_Rebel.png", "Tigers Blood Rebel Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Tricky_Tre_Rebel.png", "Tricky Tre Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Trixie_Rebel.png", "Trixie Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Tropical_Rebel.png", "Tropical Rebel"],
        ["../../assets/dutch_bro_drinks/Rebels/Unicorn_Blood_Rebel.png", "Unicorn Blood Rebel"]
       
    ],
    // Smoothies
    [
        ["../../assets/dutch_bro_drinks/Smoothies/Blueberry_Pomegranate_Smoothie.png", "Blueberry Pomegranate Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Caramel_Apple_Smoothie.png", "Caramel Apple Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Green_Apple_Smoothie.png", "Green Apple Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Mango_Smoothie.png", "Mango Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Peach_Smoothie.png", "Peach Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Strawberry_Smoothie.png", "Strawberry Smoothie"],
        ["../../assets/dutch_bro_drinks/Smoothies/Wildberry_Smoothie.png", "Wildberry Smoothie"]
        
    ],
    // Sodas
    [
        ["../../assets/dutch_bro_drinks/Sodas/Aftershock_Soda.png", "Aftershock Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Amaretto_Soda.png", "Amaretto Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Aquaberry_Soda.png", "Aquaberry Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Astronaut_Soda.png", "Astronaut Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Bubblegum_Soda.png", "Bubblegum Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Cotton_Candy_Soda.png", "Cotton Candy Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Dinosaur_Egg_Soda.png", "Dinosaur Egg Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Double_Rainbro_Soda.png", "Double Rainbro Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Dragon_Slayer_Soda.png", "Dragon Slayer Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Dutch_Mojito_Soda.png", "Dutch Mojito Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Eclipse_Soda.png", "Eclipse Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Electric_Berry_Soda.png", "Electric Berry Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Fire_Lizard_Soda.png", "Fire Lizard Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Freedom_Soda.png", "Freedom Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Galaxy_Fish_Soda.png", "Galaxy Fish Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Gem_Berry_Soda.png", "Gem Berry Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Grape_Soda.png", "Grape Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Gummy_Bear_Soda.png", "Gummy Bear Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Hawaiian_Soda.png", "Hawaiian Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Hyperchrome_Soda.png", "Hyperchrome Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Irie_Soda.png", "Irie Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Lazer_Cat_Soda.png", "Lazer Cat Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Majestic_Forest_Soda.png", "Majestic Forest Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Marmalade_Soda.png", "Marmalade Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Midnight_Soda.png", "Midnight Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/OG_Gummy_Bear_Soda.png", "OG Gummy Bear Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Orangesicle_Soda.png", "Orangesicle Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Palm_Beach_Soda.png", "Palm Beach Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Palm_Tree_Soda.png", "Palm Tree Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Passion_Water_Soda.png", "Passion Water Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Peach_Cobbler_Soda.png", "Peach Cobbler Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Peach_Ring_Soda.png", "Peach Ring Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Pink_Flamingo_Soda.png", "Pink Flamingo Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Ray_of_Sunshine_Soda.png", "Ray of Sunshine Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Red,_White_&_Blue_Soda.png", "Red, White & Blue Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Rocky_Point_Soda.png", "Rocky Point Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Shark_Attack_Soda.png", "Shark Attack Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Soda_Trixie_Iced.png", "Trixie Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Starry_Night_Soda.png", "Starry Night Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Stop_Light_Soda.png", "Stop Light Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Sweet_Sunrise_Soda.png", "Sweet Sunrise Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/The_Juice_Soda.png", "The Juice Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/The_Vampire_Slayer_Soda.png", "The Vampire Slayer Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Tigers_Blood_Soda.png", "Tigers Blood Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Tricky_Tre_Soda.png", "Tricky Tre Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Tropical_Soda.png", "Tropical Soda"],
        ["../../assets/dutch_bro_drinks/Sodas/Unicorn_Blood_Soda.png", "Unicorn Blood Soda"]
        
    ],
    // Tea
    [
        ["../../assets/dutch_bro_drinks/Tea/Aftershock_Tea.png", "Aftershock Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Aquaberry_Tea.png", "Aquaberry Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Astronaut_Tea.png", "Astronaut Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Cinammon_Spice_Iced_Tea.png", "Cinammon Spice Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Decaf_Ceylon_Iced_Tea.png", "Decaf Ceylon Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Double_Rainbro_Iced_Tea.png", "Double Rainbro Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Double_Rainbro_Tea.png", "Double Rainbro Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Dragon_Slayer_Tea.png", "Dragon Slayer Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Dutch_Mojito_Tea.png", "Dutch Mojito Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Earl_Grey_Iced_Tea.png", "Earl Grey Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Eclipse_Tea.png", "Eclipse Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Electric_Berry_Iced_Tea.png", "Electric Berry Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Fire_Lizard_Tea.png", "Fire Lizard Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Freedom_Iced_Tea.png", "Freedom Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Galaxy_Fish_Green_Tea.png", "Galaxy Fish Green Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Gem_Berry_Green_Tea.png", "Gem Berry Green Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Grape_Green_Tea.png", "Grape Green Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Green_Tea.png", "Green Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Green_Tea_Lemonade.png", "Green Tea Lemonade"],
        ["../../assets/dutch_bro_drinks/Tea/Hawaiian_Iced_Tea.png", "Hawaiian Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Hyperchrome_Tea.png", "Hyperchrome Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Iced_Green_Tea.png", "Iced Green Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Iced_Paris_Tea.png", "Iced Paris Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Irie_Iced_Tea.png", "Irie Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Lazer_Cat_Iced_Tea.png", "Lazer Cat Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Majestic_Forest_Tea.png", "Majestic Forest Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Marmalade_Tea.png", "Marmalade Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Midnight_Iced_Tea.png", "Midnight Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/OG_Gummy_Bear_Tea.png", "OG Gummy Bear Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Orangesicle_Iced_Tea.png", "Orangesicle Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Palm_Beach_Tea.png", "Palm Beach Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Palm_Tree_Tea.png", "Palm Tree Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Paris_Tea.png", "Paris Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Passion_Water_Iced_Tea.png", "Passion Water Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Ray_Of_Sunshine_Tea.png", "Ray of Sunshine Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Red,_White_&_Blue_Iced_Tea.png", "Red, White & Blue Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Rocky_Point_Tea.png", "Rocky Point Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Shark_Attack_Iced_Tea.png", "Shark Attack Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Starry_Night_Iced_Tea.png", "Starry Night Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Stop_Light_Iced_Tea.png", "Stop Light Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Sweet_Sunrise_Iced_Tea.png", "Sweet Sunrise Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/The_Juice_Tea.png", "The Juice Tea"],
        ["../../assets/dutch_bro_drinks/Tea/The_Vampire_Slayer_Iced_Tea.png", "The Vampire Slayer Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Tigers_Blood_Iced_Tea.png", "Tigers Blood Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Tricky_Tre_Iced_Tea.png", "Tricky Tre Iced Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Trixie_Tea.png", "Trixie Tea"],
        ["../../assets/dutch_bro_drinks/Tea/Tropical_Tea.png", "Tropical Tea"]
        
    ]
]

export default DrinkArray;